# This file was generated by GoReleaser. DO NOT EDIT.
class Asd < Formula
  desc "CLI tool for communicating with asd to interact with messages"
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradford-hamilton/a-scanner-darkly/releases/download/v0.1.0/a-scanner-darkly_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "bcc370f095d85cccde84e69c67776a5648c7ac4ed81ade33163a0e2f308bdcf0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradford-hamilton/a-scanner-darkly/releases/download/v0.1.0/a-scanner-darkly_0.1.0_Linux_x86_64.tar.gz"
      sha256 "1719037912258a475a28634ca1460628219d868afbc3a43f8cf3ffeccbc51e9d"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "asd"
  end
end
